# Generated by Django 2.1.5 on 2019-02-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_1', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ticker_2', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('timestamp', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'watchlist',
            },
        ),
    ]
