# Generated by Django 2.1.5 on 2019-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradelogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(default=None, null=True)),
                ('insert_type', models.CharField(default=None, max_length=30, null=True)),
                ('strategy', models.CharField(default=None, max_length=30, null=True)),
                ('product_type', models.CharField(default=None, max_length=30, null=True)),
                ('asset', models.CharField(default=None, max_length=30, null=True)),
                ('currency', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('open_date', models.CharField(default=None, max_length=30, null=True)),
                ('open_time', models.CharField(default=None, max_length=30, null=True)),
                ('open_price', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('ul_open', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('true_exposure', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('fx_open', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('net_open_sek', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('close_date', models.CharField(default=None, max_length=30, null=True)),
                ('close_time', models.CharField(default=None, max_length=30, null=True)),
                ('ul_close', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('fx_close', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('net_close_sek', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('commission', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('net_result_sek', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('mf_finlevel', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('opt_type', models.CharField(default=None, max_length=30, null=True)),
                ('opt_date', models.CharField(default=None, max_length=30, null=True)),
                ('opt_strie', models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True)),
                ('user', models.CharField(default=None, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tradelog',
            },
        ),
    ]
