# Generated by Django 2.1.5 on 2019-01-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradelogmodel',
            old_name='opt_strie',
            new_name='opt_strike',
        ),
        migrations.AddField(
            model_name='tradelogmodel',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=10, null=True),
        ),
    ]
