# Generated by Django 2.1.5 on 2019-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0003_auto_20190127_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelogmodel',
            name='currency',
            field=models.CharField(blank=True, default='SEK', max_length=4, null=True),
        ),
    ]
