# Generated by Django 2.1.5 on 2019-01-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiperDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('asset', models.CharField(max_length=30)),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'piperdb',
            },
        ),
    ]
