# Generated by Django 2.1.5 on 2019-01-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piperdatabase', '0004_piperdatabase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piperdatabase',
            name='closing_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='piperdatabase',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='piperdatabase',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='piperdatabase',
            name='opening_price',
            field=models.FloatField(),
        ),
    ]
