# Generated by Django 2.1.5 on 2019-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piperdatabase', '0005_auto_20190125_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piperdatabase',
            name='date',
            field=models.DateField(),
        ),
    ]
