# Generated by Django 2.1.5 on 2019-01-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piperdatabase', '0006_auto_20190125_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piperdatabase',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
