# Generated by Django 2.1.5 on 2019-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piperdatabase', '0007_auto_20190125_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piperdatabase',
            name='closing_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piperdatabase',
            name='high_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piperdatabase',
            name='low_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piperdatabase',
            name='opening_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
