# Generated by Django 2.1.5 on 2019-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField()),
                ('strategy', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=30)),
                ('open_date', models.CharField(max_length=30)),
                ('open_time', models.CharField(max_length=30)),
                ('true_exposure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('asset', models.CharField(max_length=30)),
                ('ul_open', models.DecimalField(decimal_places=3, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mf_finlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('commission', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
    ]
