# Generated by Django 2.1.5 on 2019-01-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190126_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='opt_strie',
            new_name='close_price',
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='opt_strike',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=10, null=True),
        ),
    ]
