# Generated by Django 2.1.5 on 2019-02-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190127_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='currency',
            field=models.CharField(blank=True, default='SEK', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='product_type',
            field=models.CharField(blank=True, choices=[('mini future', 'Mini future'), ('mini short', 'Mini short'), ('mini long', 'Mini long'), ('stock', 'Stock'), ('option', 'Option'), ('mixed', 'Mixed')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='strategy',
            field=models.CharField(blank=True, choices=[('pairs trade', 'Pairs trade'), ('standard', 'Standard'), ('iron condor', 'Iron condor'), ('covered call', 'Covered call')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='user',
            field=models.CharField(blank=True, choices=[('jesper', 'Jesper'), ('mikael', 'Mikael')], default=None, max_length=30, null=True),
        ),
    ]
