# Generated by Django 2.1.5 on 2019-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190206_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='opt_type',
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='product_type',
            field=models.CharField(blank=True, choices=[('mini short', 'Mini short'), ('mini long', 'Mini long'), ('stock', 'Stock'), ('call option', 'Call option'), ('put option', 'Put option'), ('future', 'Future'), ('etf', 'ETF')], default=None, max_length=30, null=True),
        ),
    ]
