# Generated by Django 2.1.5 on 2019-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190207_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='fx_close',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='fx_open',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10, null=True),
        ),
    ]
