# Generated by Django 2.1.5 on 2019-01-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addposition', '0002_auto_20190121_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpositionmodel',
            name='asset',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='close_date',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='close_time',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='commission',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='currency',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='fx_close',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='fx_open',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='mf_finlevel',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='net_close_sek',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='net_open_sek',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='net_result_sek',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='open_date',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='open_price',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='open_time',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='opt_date',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='opt_strie',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='opt_type',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='product_type',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='strategy',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='trade_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='trade_type',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='true_exposure',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='ul_close',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='ul_open',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addpositionmodel',
            name='user',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
